// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8xN8lBK1cM2X3mZV8i3Xb7fFZzYwyE8o',
    appId: '1:169715592986:web:55f07849c200e7269306a3',
    messagingSenderId: '169715592986',
    projectId: 'mini-campus-connect',
    authDomain: 'mini-campus-connect.firebaseapp.com',
    storageBucket: 'mini-campus-connect.appspot.com',
    measurementId: 'G-2QW9RX7TGT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADm4m7KeGmQ54Zpb9H_eQPX24KluYwSwk',
    appId: '1:169715592986:android:421e068a848cee4f9306a3',
    messagingSenderId: '169715592986',
    projectId: 'mini-campus-connect',
    storageBucket: 'mini-campus-connect.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZIiqEe5EU0kkaTNMDg24wE5oe_lltijE',
    appId: '1:169715592986:ios:0805b51cdf7083b49306a3',
    messagingSenderId: '169715592986',
    projectId: 'mini-campus-connect',
    storageBucket: 'mini-campus-connect.appspot.com',
    iosBundleId: 'com.example.miniCampusConnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZIiqEe5EU0kkaTNMDg24wE5oe_lltijE',
    appId: '1:169715592986:ios:0805b51cdf7083b49306a3',
    messagingSenderId: '169715592986',
    projectId: 'mini-campus-connect',
    storageBucket: 'mini-campus-connect.appspot.com',
    iosBundleId: 'com.example.miniCampusConnect',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8xN8lBK1cM2X3mZV8i3Xb7fFZzYwyE8o',
    appId: '1:169715592986:web:344195a7e0b185da9306a3',
    messagingSenderId: '169715592986',
    projectId: 'mini-campus-connect',
    authDomain: 'mini-campus-connect.firebaseapp.com',
    storageBucket: 'mini-campus-connect.appspot.com',
    measurementId: 'G-88DZK7CEDE',
  );
}
